/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const SkuId = IDL.Text;
export const Sku = IDL.Record({
  'id' : SkuId,
  'size' : IDL.Nat,
  'stock' : IDL.Nat,
});
export const ProductCategory = IDL.Variant({
  'sandals' : IDL.Null,
  'sneakers' : IDL.Null,
  'heels' : IDL.Null,
  'boots' : IDL.Null,
  'formal' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Sku),
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const SessionId = IDL.Text;
export const Quantity = IDL.Nat;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'skuId' : SkuId,
  'quantity' : Quantity,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'addToCart' : IDL.Func([SessionId, CartItem], [], []),
  'filterProductsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Principal, SessionId, ShippingAddress],
      [IDL.Nat],
      [],
    ),
  'removeFromCart' : IDL.Func([SessionId, ProductId, SkuId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const SkuId = IDL.Text;
  const Sku = IDL.Record({ 'id' : SkuId, 'size' : IDL.Nat, 'stock' : IDL.Nat });
  const ProductCategory = IDL.Variant({
    'sandals' : IDL.Null,
    'sneakers' : IDL.Null,
    'heels' : IDL.Null,
    'boots' : IDL.Null,
    'formal' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Sku),
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const SessionId = IDL.Text;
  const Quantity = IDL.Nat;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'skuId' : SkuId,
    'quantity' : Quantity,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'addToCart' : IDL.Func([SessionId, CartItem], [], []),
    'filterProductsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Principal, SessionId, ShippingAddress],
        [IDL.Nat],
        [],
      ),
    'removeFromCart' : IDL.Func([SessionId, ProductId, SkuId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };