/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : ProductId,
  'skuId' : SkuId,
  'quantity' : Quantity,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'sizes' : Array<Sku>,
  'imageUrl' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'sandals' : null } |
  { 'sneakers' : null } |
  { 'heels' : null } |
  { 'boots' : null } |
  { 'formal' : null };
export type ProductId = bigint;
export type Quantity = bigint;
export type SessionId = string;
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
}
export interface Sku { 'id' : SkuId, 'size' : bigint, 'stock' : bigint }
export type SkuId = string;
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], ProductId>,
  'addToCart' : ActorMethod<[SessionId, CartItem], undefined>,
  'filterProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'placeOrder' : ActorMethod<[Principal, SessionId, ShippingAddress], bigint>,
  'removeFromCart' : ActorMethod<[SessionId, ProductId, SkuId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];